#!/bin/bash

db=$1
mongorouter=`cat /etc/mongorouter.conf | tr "\n" "," | sed -e 's/.$//g'`

log=`echo "db.runCommand({enablesharding : '$db'})" | mongo $mongorouter/admin --quiet`
echo $log

echo $log | grep '"ok" : 1' && exit 0 || exit 1
