#!/bin/bash

db=$1
mongorouter=`cat /etc/mongorouter.conf | tr "\n" "," | sed -e 's/.$//g'`

echo "db.printShardingStatus()" | mongo $mongorouter/admin --quiet | grep '"_id" : "'$db'", "partitioned" : true'
